### ISSUE TITLE
Array out of bounds issue in client test

### ISSUE THREAD

**Issue by 7sharp9** [fractureio/fracture#1]
Array out of bounds issue in client test, this is an issue in the server, could be the common code

**Comment by 7sharp9** [comment]
Its not an array out of bounds but a port setting of address that is invalid in IPAddress.Create.

Im not sure how this occurs yet but it must be a race condition.

**Comment by panesofglass** [comment]
You've sorted this one, haven't you?

**Comment by 7sharp9** [comment]
This no longer occurs, the fix was to slit the connect pool out.
