### ISSUE TITLE
Redesign architecture

### ISSUE THREAD

**Issue by panesofglass** [fractureio/fracture#10]
The core concept of fracture was intended to be a fully composable pipeline of socket "pipelet" messengers, similar to 0mq. The `TcpServer` type goes against this ideal and should be deconstructed into several smaller components:
1. `SocketListener` - accepts incoming sockets
2. `SocketConnection` - receives and sends data through a connected socket (this might be better as two components)
3. A composition of the above built around Tcp (the same could hold for other protocols such as UDP).

Atop this could be built further components, such as an HTTP server.

**Comment by panesofglass** [comment]
I've already added async socket extensions in commit 8aef517fcfb24282e6e599fca487918b84ffe7ce

**Comment by panesofglass** [comment]
Further clarification: you should be able to compose a `TcpServer` from a pool of `SocketListener`s (to accept) and a pool of `SocketConnection`s (for receive and send), as well as settings to inform the sockets to use TCP. A similar thing should allow for a `UdpServer`. Additionally, an `HttpServer` should then be composable by applying a parser and logic for handling HTTP headers.

**Comment by 7sharp9** [comment]
Im  not sure how possible this will be, a lot of control will be yielded as a result.  A strong control over resources is essential too so this needs to be discussed.  Again pseudo code demonstrating this would be ideal, there may be unseen dependencies here...

**Comment by panesofglass** [comment]
Agreed. This is just an idea. Another idea is that agents are really just `async` loops. We could construct a lightweight (i.e. non-thread-bound) `Pipelet` that could represent the two loops, one for accepting connections and one for handling receive and send processes. That should keep both resource and thread management under control.

**Comment by 7sharp9** [comment]
Maybe 3 agents- connect, send, receive.  The only problem is getting the saea's into the agents without allocating objects, or at least without them over weighing the advantage of almost allocation free sara model...

**Comment by 7sharp9** [comment]
Agents are far too slow for this.  Async loops might be quite slow too, this is so long ago I think we should close this  for now.
