### ISSUE TITLE
Replace Concurrent .NET 4.0 data structures with functional data structures

### ISSUE THREAD

**Issue by panesofglass** [fractureio/fracture#11]
We currently use `ConcurrentDictionary` and `BlockingCollection` which require .NET 4.0. To get back to .NET 3.5 portability, we need to use purely functional data structures such as [`ObjectPool`](https://github.com/fractureio/fracture/commit/715a3c726aa7c9579eff2f5f77185138208af683) or [`BlockingQueueAgent`](https://github.com/fsharp/fsharpx/blob/master/src/FSharpx.AsyncExtensions/Agents/BlockingQueueAgent.fs).

**Comment by panesofglass** [comment]
`ObjectPool` is back, and I've updated my [ObjectPool branch](http://github.com/panesofglass/fracture/tree/ObjectPool). However, performance now seems to have degraded. I'm not sure what has happened, but I didn't want to push this in until we had determined the best solution.

**Comment by 7sharp9** [comment]
Is it possible to abstract the object pool and the alternative so we can compare just this subsystem in context with the  rest of the system?

**Comment by panesofglass** [comment]
What do you mean by "alternative"? Also, now that I've added `FSharpx` as a dependency, we have access to the `BlockingQueueAgent` if we want to use it.

**Comment by 7sharp9** [comment]
I only remember the blocking agent queue to be honest...

**Comment by panesofglass** [comment]
Ah, I see. You mean `ObjectPool` vs. `BlockingQueueAgent` vs. `BlockingCollection`? If so, I can spin up another branch to test. It might be possible to define `ObjectPool` in terms of `BlockingAgentQueue`, esp. since we have a `TODO` to essentially implement a blocking mechanism already developed in the `BlockingAgentQueue`.

**Comment by 7sharp9** [comment]
Refresh my memory, how was the object pool used?

Also .Net 3.5 compatibility why do we need that?  Surely the garbage collector improvements in .Net might be beneficial, and going forward the .Net 4.5 further improvements.

Going forward we will have to recompile and target that to see if there are any improvements.

**Comment by 7sharp9** [comment]
Maybe just test them on there own, i.e. add and remove 1,000,000 to each 0.1ms per operation is what we are aiming for...

**Comment by 7sharp9** [comment]
I don't think this issue is valid, its not a question of functional vs .Net 4.0 concurrent structures, we just need to use the fastest as thats the whole point.
