### ISSUE TITLE
Split Buffer and SocketAsyncEventArgs Pools

### ISSUE THREAD

**Issue by panesofglass** [fractureio/fracture#12]
We need to split these two pools and set the `SocketAsyncEventArgs.SetBuffer` each time an `args` is used. This allows us more flexibility for how we use memory and may allow us to avoid `Buffer.BlockCopy` for operations where that is unnecessary. This further allows us a more flexible socket management scheme should we move to using the async extensions.

**Comment by 7sharp9** [comment]
How do you propose we manage 'setting' the buffer, won't this just mean we have to manage another pool of buffer offsets so that we know which offsets are available?

**Comment by panesofglass** [comment]
Yes, that's correct. We'd end up with 4 or 5 pools if we do this:
1. Buffer pool for Accept `SocketAsyncEventArgs` (optional for perf)
2. Buffer pool for Receive/Send `SocketAsyncEventArgs`
3. `Socket` pool for connections (#13)
4. `SocketAsyncEventArgs` pool for connections
5. `SocketAsyncEventArgs` pool for receive/send

**Comment by ghost** [comment]
I just came across this issue from Google randomly, noticed fracture is a socket library for F#, you guys got any plans to develop something for C# with using 'SocketAsyncEventArgs'?

& Yes with the pools you have a pool for accepting connections and a pool for sending/receiving data as well as allocating one big byte[] block for connections to use (avoids allocating and re-allocating the buffer each time which can reduce performance and cause memory fragmentation on the heap)

**Comment by 7sharp9** [comment]
Hi Matty, we currently have no plans to develop anything in C#.

I did develop a C# implementation about 3 years ago and this is an evolution on that.  
(Less code and complexity and more performant in F#)

We do however plan on the library being callable from C# once the API has solidified.  At the moment we are in the processing of merging some of our branches together for the new version.

**Comment by ghost** [comment]
Sounds awesome! I'll keep checking back here to see your progress on this be interesting to use this within C# :)

**Comment by panesofglass** [comment]
@ghost If you are interested, we're open to pull requests. :) If you would like to write up the C# api and help hook this up -- when it's ready -- we'd appreciate it!

**Comment by panesofglass** [comment]
@ghost You can find a C# sample at https://github.com/fractureio/fracture/blob/master/samples/CSharpServer/Program.cs

**Comment by panesofglass** [comment]
I think we've worked around this issue. If nothing else, it's ancient. I'm closing it for now.
