### ISSUE TITLE
TcpServer callbacks signature

### ISSUE THREAD

**Issue by hammett** [fractureio/fracture#15]
Could you consider changing the signature of connected/disconnected/sent to match received? IOW SocketDescriptor instead of endpoint. The issue is how comparable/unique an IPEndPoint may be, I had issues with it in a hash table, and changing to SD fixed it.

**Comment by 7sharp9** [comment]
The SocketDescriptor was added by me to get around EndPoints not being accessible after the socket was disposed.  Which branch are you using?  There are a few parallel branches going on at the moment...

**Comment by hammett** [comment]
I'm using master, with quite a few changes.
