### ISSUE TITLE
Remove F# dlls from repo, rely on msbuild targets

### ISSUE THREAD

**Issue by 7sharp9** [fractureio/fracture#28]

**Comment by panesofglass** [comment]
Fixed in c6739e3c1850a337f165e09e82debf10404d49ea

**Comment by panesofglass** [comment]
I think I misunderstood this one. Many .dll files have been removed. Removing the lib folder causes headaches on TeamCity: http://teamcity.codebetter.com/viewLog.html?tab=buildLog&buildTypeId=bt1151&buildId=102314

**Comment by panesofglass** [comment]
I'll look at moving this to VSO. TeamCity has been causing me too much pain. @forki, do you have any advice on getting builds working on TeamCity without the lib/FSharp folder?

**Comment by 7sharp9** [comment]
@panesofglass Maybe try a travis build.

**Comment by panesofglass** [comment]
I want to add that, but I can't get any travis builds working for my other, simpler projects. I need to follow up with @forki to see if he has any suggestions. The current problem is NuGet.Core.dll cannot be found. (See frank and VegaHub projects.)
