### ISSUE TITLE
HttpServer - HTTP POSTs with body appear not to be working

### ISSUE THREAD

**Issue by kjnilsson** [fractureio/fracture#32]
Whenever I POST an http request including a request body to the HttpServer it never hits the body and requestEnd delegates. Presumably this is because you create a new ParserDelegate for each TcpServer 'received' callback and you get more than one per request. (line 35 in HttpServer.fs). I had a quick look but couldn't see an easy and nice way to fix this though due to the partial application going on. The ParserDelegate needs per-request scope I think.

**Comment by panesofglass** [comment]
You are correct. I'm currently working on a replacement. Watch https://github.com/panesofglass/fracture/tree/owin-new for progress. (Yes, the last commits were long ago in that repo, but I have a lot of current work on that branch not yet pushed.)

**Comment by kjnilsson** [comment]
cool - nice one.

**Comment by panesofglass** [comment]
@kjnilsson I know it's been awhile, but would you mind checking #36 to see if that resolves your issue?

**Comment by panesofglass** [comment]
@kjnilsson I'm now getting notices of issues and PRs. I think I fixed the issue above. Would you mind checking?

**Comment by kjnilsson** [comment]
Apologies for not looking at this earlier. I appear to have lost the test project I was playing with fracture in. Is this change in the latest nuget package?

**Comment by kjnilsson** [comment]
I get this when trying to install the Fracture.Http package:

Attempting to resolve dependency 'Fracture (≥ 0.9.1)'.
Attempting to resolve dependency 'HttpMachine (≥ 0.9.0.0)'.
Child dependencies of dependency only packages cannot mix external and project packages.

Did you pack it with -IncludeReferencedProjects?

**Comment by panesofglass** [comment]
@kjnilsson Interesting that this didn't use to be a problem. The Fracture.Http package should not be a dependency only package. I'm investigating but probably won't have a fix until tonight.

**Comment by panesofglass** [comment]
Looks like packaging is not working properly for either Fracture or Fracture.Http.

**Comment by panesofglass** [comment]
I split the repos, and the packages appear to be working properly now. Please try again, if you don't mind.
