### ISSUE TITLE
http://fractureio.net/ redirects to spam

### ISSUE THREAD

**Issue by TWith2Sugars** [fractureio/fracture#46]

**Comment by panesofglass** [comment]
Thanks! I bet @7sharp9 let the domain go.

**Comment by 7sharp9** [comment]
I thought @panesofglass was in charge

**Comment by panesofglass** [comment]
@7sharp9, that could be true. We must have agreed to let it go. :)

**Comment by 7sharp9** [comment]
It would be nice to give fracture a new lease of life, I enjoyed working on it with you.  :-)

**Comment by panesofglass** [comment]
Likewise! Next major hurdle is to get this running on top of libuv. @TIHan said he would help with that.
