### ISSUE TITLE
HTTP Request Body Parsers

### ISSUE THREAD

**Issue by panesofglass** [fractureio/fracture#7]
Not exactly sure what needs to be included here, but at a bare minmum:
1. EmptyBody
2. FormUrlEncodedBody of (string \* string) list
3. XmlBody of XElement
4. JsonBody of string
5. StringBody of string
6. ByteArrayBody of byte[]

... or should this just be part of the [conneg](http://en.wikipedia.org/wiki/Conneg) infrastructure and be extensible?

**Comment by panesofglass** [comment]
This could be interesting if we want to start offering type provider support on the raw bytes.

**Comment by mausch** [comment]
With "type provider support on the raw bytes" you mean a parser built from an model request, similarly to JsonProvider?
