### ISSUE TITLE
Investigate 'bytes needed during connection' problem

### ISSUE THREAD

**Issue by 7sharp9** [fractureio/fracture#8]
If you do not set a buffer during connection, are there bytes present in the accepted socket message?

**Comment by panesofglass** [comment]
The documentation notes that you can optionally supply a buffer. I imagine if we took away the buffer, we wouldn't pick up any data at that point. However, as you mentioned, it's an optimization that might help.

**Comment by 7sharp9** [comment]
Are you going to test this?

**Comment by panesofglass** [comment]
I can.
